name=input( "who are u?")
city=input("where do you live?")
age=input("how old u are?")
hobby=input("what is ur hobby?")
movie=input("what is ur favorite movie?")
food=input("what is ur favorite food?")

print ("-----your details fillled by you----")
print ("name:",name)
print ("city:",city)
print ("age:",age)
print("hobby:",hobby)
print("movie:",movie)
print("food:",food)
print("---the end---") 